### ISSUE TITLE
Define rule DDF00020: The study protocol may have conditional activities, these must have   reasons or conditions for the activity.

### ISSUE THREAD

**Issue by nickdedonder** [cdisc-org/ddf-core-poc#22] opened 2023-10-23 08:22 UTC

**Comment by rbakercdisc1** [comment] 2023-11-13 16:29
@nickdedonder 
This check is checking for actual conditional activities in the protocol against the reason. We discussed redoing this since it is not part of the USDM.
I thought there was a codelist for reason for the condition but there isn't. There is already another check for if Activity or Procedure is conditional then there must be a reason. The thought was this was the reverse of the rule.
I was going to change this to another rule until we discussed the potential of keeping these. Please advise. 

First, is it valid the (reverse), I am leaning towards not.
Second, may I reuse the number.

**Comment by drewcdisc** [comment] 2023-11-16 14:34
This is a duplicate of #31

**Closed by drewcdisc** 2023-11-16 14:34 UTC
