### ISSUE TITLE
Support USDM data source in Engine

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/ddf-core-poc#35] opened 2023-10-24 17:54 UTC
The USDM json data needs to be parsed and converted to a dataset format that can be used by the engine

**Comment by drewcdisc** [comment] 2023-12-14 14:35
This ticket would make it possible to run an entire study with an entire set of rules.  @nickdedonder , Gerry believes this should be the number one priority for rule engine work.

**Comment by ASL-rmarshall** [comment] 2024-01-11 16:48
@gerrycampion 
I have been thinking about the "scope" of the transformation from JSON to dataframes in light of some of the discussions we've been having about uniqueness.  It seems that there will be some rules that do checks within different scopes of the hierarchical JSON structure. For example:
- The value of the `id` attribute for all instances of all classes must be unique *within each (instance of) StudyVersion* (the same instance of a class with the same `id` value may appear in more than one version of the study).
- There must be a one-to-one relationship between the values of `name` and `description`/`label`/`text` *within each (instance of) StudyDesign* (although it might be considered bad practice, it would be allowable for a `name` value to be associated with different `description`/`label`/`text` values in different study designs within the same study).

We've been considering how to perform checks with different contexts (e.g., using the `within` check parameter), but it's occurred to me that - in the test data template at least - the `id` value for StudyVersion and/or StudyDesign is not propagated into the sheets representing sub-classes with StudyVersion and/or StudyDesign.  This would therefore make it difficult to perform some "within" checking because the differentiating identifier values would not be directly associated with the data (so they'd probably have to be added in some way - e.g. through dataset joining).

This makes me wonder whether it might be an idea to define the "data scope" for rule execution - i.e., instead of expecting to execute all rules across the full study definition included in a USDM JSON data stream/file (e.g., including all study designs within all study versions), perhaps we could define the "data scope" for rule execution as a single study design within a single study version.  If the data includes multiple study versions and/or multiple study designs, might it be better to iterate through these and perform dataframe generation and rule execution for each unique study version/study design combination (possibly allowing version/design to be specified as a filter)?

**Comment by ASL-rmarshall** [comment] 2024-01-25 19:27
@gerrycampion I have a question about how you're implementing combination of parent and child classes when the child is not in an array.  Will you only represent the data in the dataset for the parent, or will you also represent it in a dataset corresponding with the child class?

This will make a difference to rule specifications.  For example, the rule for #114 could be implemented simply by checking for a "not unique set" of `code.code` within `parent_id` if both primary and secondary reasons are represented in the `StudyAmendmentReason` dataset. But given that there can be no more than one primary reason for a study amendment, I'd expect the primary reason attributes to be represented in the (parent) `StudyAmendment` dataset - so will the code for the primary reason be represented only in the `StudyAmendment` dataset, or will it also be represented as a separate row (with `parent_rel` = "primaryReason") in the `StudyAmendmentReason` dataset?

**Comment by gerrycampion** [comment] 2024-01-25 20:13
@ASL-rmarshall  I've started implementing it the first way (just the parent), but I will update it so that it will work both ways.

**Comment by ASL-rmarshall** [comment] 2024-02-19 13:45
@gerrycampion While I think that the inclusion of the `rel_type` column (and the inclusion of "reference" instances in the data) is a good idea - it will certainly be helpful for check's like "`nextId` and `previousId` must be complementary" - this is going to have an impact both on the test data template (which will need to be updated to include the column), and on quite a few of the checks that have already been created and marked as "Done".  For these checks, the test data will need to be moved to the updated template with the `rel_type` column populated and, if necessary, the check logic will need to be updated to include/exclude records based on the `rel_type` value.  For example, records checking for uniqueness will need to exclude records where `rel_type = relationship`.

FYI - @nickdedonder @BSnoeijerCD @DianeWold @drewcdisc

**Comment by RamilCDISC** [comment] 2024-04-18 21:52
The issue is clear from QA validation. The engine now successfully support USDM data sources. The code changes were validated and found to be up to the standards. Following test cases were run

1. Validate run with usdm dataset (positive)
2. Validate run with usdm dataset (negative)
3. Test run with usdm dataset( positive)
4. Test run with usdm dataset (negative)
5. Validate run for non usdm datasets (regression tests)
6. Test runs for non usdm datasets (regression tests)
7. Check if new support of data source integrates well
8. Check if usdm datasets cause major performance issues
9. Test run with usdm rules for positive usdm datasets
10. Test run with usdm rules for negative usdm datasets

The new code changes successfully passed the test cases. But it was observed that after the changes now when validation is run the engine prints current directory in the terminal. This is not the case when test command is used to run the validation. It can also be observed in the following screenshot. 

<img width="1495" alt="35 2" src="https://github.com/cdisc-org/ddf-core-poc/assets/113539111/95905614-4c86-4f35-a1c9-40ffe3a6d88e">

**Closed** 2024-04-19 15:20 UTC
