### ISSUE TITLE
Define rule: A StudyAmendment reason linked to a StudyAmendment as the primaryReason cannot also be linked as a secondayReason.

### ISSUE THREAD

**Issue by DianeWold** [cdisc-org/ddf-core-poc#132] opened 2024-01-23 13:50 UTC
From Berber's list: "StudyAmendmentReason is only referred to once: as primaryReason or as secondaryReason. (check of uniqueness of referenced id value)"
Since only one primary reason is allowed (and would be part of the cardinality schema checking), the check above means the primary reason cannot also be a secondary reason.

**Comment by ASL-rmarshall** [comment] 2024-01-24 18:58
@DianeWold I think this might be a duplicate of #114

**Comment by DianeWold** [comment] 2024-01-25 13:32
Yes, it does seem to be a duplicate, though it's a slightly different approach, trying to use the fact that there can be only one primaryReason.

**Comment by nickdedonder** [comment] 2024-01-29 16:21
duplicate of https://github.com/cdisc-org/ddf-core-poc/issues/114

**Closed by nickdedonder** 2024-01-29 16:21 UTC
